### ISSUE TITLE
Render won't happen if html file is called index

### ISSUE THREAD

**Issue by dxxxxy** [str1z/wagon-engine#1]
With this code:
```js
//js
app.get("/", (req, res) => {
    res.send(wge.render(path.join(__dirname, "public/main.html"), { version }))
})
```
```html
<!--- html --->
<p>Slaysim<sup>v{data.version}</sup></p>
```
the page works as intended.
![image](https://user-images.githubusercontent.com/42523606/148590504-24f07333-4332-446a-8593-e92a9d306a17.png)

However, if we simply rename the file to `index.html` and change the path in express from `"public/main.html"` to `"public/index.html"`,
![image](https://user-images.githubusercontent.com/42523606/148590648-1c5804a4-d6f9-4f47-a980-814235153711.png)
it doesn't render the version. 

NOTE: only the file name and the path to the file were changed.

**Comment by weisrc** [comment]
What is the filename of `main.html`'s data provider?

**Comment by weisrc** [comment]
Can you send the entire code snippet for more details?

**Comment by weisrc** [comment]
It works fine for me. I tested it with:
```js
console.log(wge.render(path.join(__dirname, "public/index.html"), { version: 2 }));
```
And everything is working as intended. Try hard reloading the page because your browser might be caching a previous iteration without the renderer.

**Comment by weisrc** [comment]
To be sure, you can console.log the rendered result.

**Comment by dxxxxy** [comment]
> And everything is working as intended. Try hard reloading the page because your browser might be caching a previous iteration without the renderer.

I forgot to mention but I'm debugging on localhost, and restarting express each time.

> To be sure, you can console.log the rendered result.

Im trying to log it with this `console.log(wge.render(path.join(__dirname, "public/index.html"), { version }))`, but it just does not render. There is no output in console when I visit the page, no undefined no null just nothingness.

Another weird thing: when its index.html, not even my console.log("test") works when I'm visiting the page. However, when its main.html it works.

```js
app.get("/", (req, res) => {
    console.log(wge.render(path.join(__dirname, "public/index.html"), { version }))
    console.log("test")
    res.send(wge.render(path.join(__dirname, "public/index.html"), { version }))
})
//nothingness
```

```js
app.get("/", (req, res) => {
    console.log(wge.render(path.join(__dirname, "public/main.html"), { version }))
    console.log("test")
    res.send(wge.render(path.join(__dirname, "public/main.html"), { version }))
})
//prints the dom, prints "test" and renders the page
```

**Comment by weisrc** [comment]
I think your express might be returning the page before it can reach your custom handler with the renderer because it is in the public folder. Try moving your templates to another directory like templates.

**Comment by dxxxxy** [comment]
> I think your express might be returning the page before it can reach your custom handler with the renderer because it is in the public folder. Try moving your templates to another directory like templates.

Well, it wouldn't make any sense, would it? Only changing the name of the file works. I've tried to rename the folder to pages or anything else. The problem is what makes `index.html` not behave in the same way as anything other because as mentioned, I only changed the name without changing anything else.

**Comment by dxxxxy** [comment]
The solution was to place `app.use(express.static("public"))` after declaring all the routes.
```js
app.get("/", (req, res) => {
    console.log(wge.render(path.join(__dirname, "public/index.html"), { version }))
    console.log("test")
    res.send(wge.render(path.join(__dirname, "public/index.html"), { version }))
})

app.use(express.static("public"))
```
This now works, thanks a lot @weisrc
